# -*- coding: utf-8 -*-
"""Problem 3(New).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MxpmerkzZjXKs4KycBINxn1zMq6GN1Up
"""

T = int(input())

def sum_of_multiples(N, divisor):
    num_of_multiples = (N - 1) // divisor
    return divisor * num_of_multiples * (num_of_multiples + 1) // 2

for _ in range(T):
    N = int(input())
    sum = (
        sum_of_multiples(N, 3)
        + sum_of_multiples(N, 5)
        - sum_of_multiples(N,15)
    )
    print(sum)