# -*- coding: utf-8 -*-
"""Problem 1(New).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_svVyLYV_0fHJbqoXyhuo6aufSTIm8iS
"""

s = input()
numbers = list(map(int, s.split()))
sum=0
for s in numbers:
  if (s % 2 !=0):
    sum=sum+s
print(sum)