# -*- coding: utf-8 -*-
"""Problem 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ga2EqcKYXeUnq3utU8xBfxEl225eGGVS
"""

def simpleArraySum(ar):
    total = sum(ar)
    return total
n = int(input())
ar = list(map(int, input().split()))
result = simpleArraySum(ar)
print(result)