# -*- coding: utf-8 -*-
"""Problem 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQGkkfPuw8fbX_4ftrC1d9ikAueCwFDI
"""

def largest_prime_factor(N):
    factor = 2

    while factor * factor <= N:
        if N % factor == 0:
            N //= factor
        else:
            factor += 1

    return N

T = int(input())
for _ in range(T):
    N = int(input())
    largest_factor = largest_prime_factor(N)
    print(largest_factor)