# -*- coding: utf-8 -*-
"""Problem 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_svVyLYV_0fHJbqoXyhuo6aufSTIm8iS
"""

def solve(nums):
    return sum(x for x in nums if x % 2 == 1)
input_str = input("Enter a list of numbers separated by spaces: ")
nums = [int(num) for num in input_str.split()]
result = solve(nums)
print(result)