# -*- coding: utf-8 -*-
"""Problem 2(New).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QtgvFvREXX8wvwdmF4riZldw_5LMCJJV
"""

n=int(input())
s=input()
num=list(map(int,s.split()))
sum=0
for s in num:
    sum=sum+s
print(sum)