# -*- coding: utf-8 -*-
"""Problem 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyBqMFHTpxC7AmvzIN76fMZXGmZ8z3FD
"""

def sum_of_multiples(n, divisor):
    n -= 1
    num_multiples = n // divisor
    return divisor * num_multiples * (num_multiples + 1) // 2

t = int(input())

for _ in range(t):
    n = int(input())

    result = (
        sum_of_multiples(n, 3)
        + sum_of_multiples(n, 5)
        - sum_of_multiples(n, 15)
    )
    print(result)